### ISSUE TITLE
Avoid the anti flood

### ISSUE THREAD

**Issue by DamianoP** [KnugiHK/synapse-admin-api-python#3]
Hey, I've used your code and it worked very well, nice job ! 
In my opinion it would be useful to insert a command that avoids running into the antiflood of synapse
For example:
I wrote a script with which I generated about 60 rooms starting from a txt file that contained their names.
The server after the fifth / sixth room started giving some errors
To solve this, I inserted a 60-second sleep between the creation of one room and the next one

In my opinion it would be useful if this library will be able to disable the antiflood with a python command, or at least make it more flexible.

**Comment by KnugiHK** [comment]
Glad that you find this wrapper useful. I assume you meant when there are too many requests within a short period, Synapse will response a M_LIMIT_EXCEEDED.

I think it is a good idea to avoid raising M_LIMIT_EXCEEDED in the wrapper. I would like to know what or which implementation you will recommend. What I can think of now are:
1. Add a lock in the wrapper and after each API called, lock the wrapper from sending requests for a while.
2. Add a lock as well as counter in the wrapper and after each API called, increase the counter. When the counter reach a set limit (e.g. 3 requests), lock the wrapper from sending requests for a while.

Both ways will be enabled by default and can be disabled by passing a bool to the API classes.

Any other suggestions are welcome.

**Comment by DamianoP** [comment]
Yes, that's right, I didn't know the exact name but I was referring to when the server returns "M_LIMIT_EXCEEDED".
Your two proposals are interesting, probably the first solution you propose would be effective but not optimal.
Since this type of code is used by system administrators, in my opinion, the optimal solution would be for the wrapper to be able to make as many requests as it wants without incurring any limitations.

**Comment by KnugiHK** [comment]
As far as I know, there is no limitation on Synapse admin API. However, room creation is not part of the official admin API and is implemented with the client API. I did some searching on matrix.org/synapse and found that the rate-limit of joining (creating) rooms through client API is set as 10 by default (see their issue [#9487](https://github.com/matrix-org/synapse/issues/9487#issuecomment-823387747)). Since the limitation is placed by Synapse, the wrapper can not remove the rate-limiting.

So, at this moment, I believe adding a lock in ClientAPI class is the best solution. And I prefer the second proposal, as there should be no limitation before reaching the default burst count.

Btw, if you need to call the client API without incurring any limitation, you may increase the burst count in the server config (homeserver.yaml)
```yaml
rc_joins:
  local:
    per_second: 0.1
    burst_count: 10 < this
```

**Comment by DamianoP** [comment]
Super, thank you !

**Comment by KnugiHK** [comment]
Finally, instead of adding a lock to prevent being rate-limited, I decided to retry the room creation (or you can say joining a room) internally. SynapseException with error code "M_LIMIT_EXCEEDED" should not be raised now in case of the limitation occurs. Therefore, you can now remove the 60s sleep and leave the burst_count as default (10).

This internal behavior is introduced in ClientAPI.client_create_room only, as room creation seems to be the only API in this wrapper limited by Synapse.

See more in commit [#f8b81e9](https://github.com/KnugiHK/synapse-admin-api-python/commit/f8b81e9205cc7ca966b433c808535285cee4f542).

**Comment by DamianoP** [comment]
excellent, I will try in the next few weeks
